"use client";

import { useRef, useState, use } from "react";
import Link from "next/link";
import ShareExportBar from "@/components/ShareExportBar";
import { getCourseById } from "@/lib/courses";
import { notFound } from "next/navigation";

export default function DefendPage({
  params,
}: {
  params: Promise<{ courseId: string }>;
}) {
  const { courseId } = use(params);
  const course = getCourseById(courseId);
  const [caseText, setCaseText] = useState("");
  const artifactRef = useRef<HTMLDivElement>(null);

  if (!course) {
    notFound();
  }

  return (
    <main className="flex flex-1 flex-col bg-surface-tint px-lg py-xl">
      <div className="flex flex-col gap-xl max-w-[480px] w-full mx-auto">
        <Link href={`/explore/${course.id}`} className="type-caption text-muted">
          ← Back to {course.name}
        </Link>

        <div className="flex flex-col gap-xs">
          <span className="type-caption text-muted uppercase tracking-wider">
            Field Defense Summary
          </span>
          <h1 className="type-display-lg text-explore">{course.name}</h1>
        </div>

        <div className="flex flex-col gap-sm">
          <h2 className="type-h2 text-main">Why this course?</h2>
          <p className="type-body text-muted">
            Make your case. Why does {course.name} fit you — your
            interests, your strengths, or something you&apos;ve seen that
            made you consider it?
          </p>
          <textarea
            value={caseText}
            onChange={(e) => setCaseText(e.target.value)}
            placeholder="Write your case here..."
            rows={6}
            className="type-body px-md py-sm rounded-lg border border-explore-border bg-surface-base text-main resize-none"
          />
        </div>

        <div className="flex flex-col gap-md">
          <h2 className="type-h2 text-main">Your Field Defense Summary</h2>

          <div
            ref={artifactRef}
            className="rounded-lg bg-surface-base border border-explore-border p-lg flex flex-col gap-sm"
          >
            <span className="type-caption text-muted uppercase tracking-wider">
              LearnedHub — Field Defense Summary
            </span>
            <h3 className="type-h1 text-explore">{course.name}</h3>
            <span className="type-caption text-muted">{course.faculty}</span>

            {course.jambSubjects && (
              <div className="flex flex-col gap-xs mt-xs">
                <span className="type-caption text-muted uppercase tracking-wider">
                  JAMB Subjects
                </span>
                <p className="type-body text-main">
                  {course.jambSubjects.join(", ")}
                </p>
              </div>
            )}

            <div className="flex flex-col gap-xs mt-xs">
              <span className="type-caption text-muted uppercase tracking-wider">
                My Case
              </span>
              <p className="type-body text-main">
                {caseText.trim() ? caseText : "[ Not yet written ]"}
              </p>
            </div>

            <span className="type-caption text-muted mt-xs">
              Generated by LearnedHub Explore
            </span>
          </div>

          <ShareExportBar
            targetRef={artifactRef}
            filename={`learnedhub-field-defense-${course.id}`}
            shareMessage={`My LearnedHub case for ${course.name}`}
            accent="explore"
          />
        </div>
      </div>
    </main>
  );
}